# NLP Exercises (Part 2)

We have 2 exercises in this section. The exercises are:

4. Build your own Bag Of Words implementation using tokenizer created before.
5. Build a 5-gram model and clean up the results.

## Exercise 4. Build your own Bag Of Words implementation using tokenizer created before 

You need to implement following methods:

- ``fit_transform`` - gets a list of strings and returns matrix with it's BoW representation
- ``get_features_names`` - returns list of words corresponding to columns in BoW

In [10]:
import numpy as np
import spacy

class BagOfWords:
    """Basic BoW implementation."""
    
    __nlp = spacy.load("en_core_web_sm")
    __bow_list = []
    
    # your code goes maybe also here    
    
    def fit_transform(self, corpus: list):
        tokenized_corpus = []
        all_words = set()
        
        for text in corpus:
            tokens = [token.text.lower() for token in self.__nlp(text) 
                      if not token.is_punct and not token.is_space]
            tokenized_corpus.append(tokens)
            all_words.update(tokens)
        
        self.__bow_list = sorted(list(all_words))
        
        matrix = np.zeros((len(corpus), len(self.__bow_list)), dtype=int)
        word_to_idx = {word: i for i, word in enumerate(self.__bow_list)}
        
        for doc_idx, doc_tokens in enumerate(tokenized_corpus):
            for token in doc_tokens:
                if token in word_to_idx:
                    matrix[doc_idx, word_to_idx[token]] += 1
        
        return matrix
      

    def get_feature_names(self) -> list:
        """Return words corresponding to columns of matrix.

        Returns
        -------
        List[str]
                Words being transformed by fit function

        """   
        # your code goes here
        return self.__bow_list

corpus = [
     'Bag Of Words is based on counting',
     'words occurences throughout multiple documents.',
     'This is the third document.',
     'As you can see most of the words occur only once.',
     'This gives us a pretty sparse matrix, see below. Really, see below',
]    
    
vectorizer = BagOfWords()

X = vectorizer.fit_transform(corpus)
print(X)

vectorizer.get_feature_names()
len(vectorizer.get_feature_names())

[[0 0 1 1 0 0 1 0 0 0 1 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0]
 [0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0]
 [0 1 0 0 0 1 0 0 0 0 0 0 1 0 1 0 1 0 1 1 0 0 1 0 1 0 0 0 0 1 1]
 [1 0 0 0 2 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 1 1 2 1 0 0 1 0 1 0 0]]


31

## Exercise 5. Build a 5-gram model and clean up the results.

There are three tasks to do:
1. Use 5-gram model instead of 3.
2. Change to capital letter each first letter of a sentence.
3. Remove the whitespace between the last word in a sentence and . ! or ?.

Hint: for 2. and 3. implement a function called ``clean_generated()`` that takes the generated text and fix both issues at once. It could be easier to fix the text after it's generated rather then doing some changes in the while loop.

In [13]:
import nltk
nltk.download('book', quiet=True)

True

In [14]:
from nltk.book import *

wall_street = text7.tokens

import re

tokens = wall_street

def cleanup():
    compiled_pattern = re.compile("^[a-zA-Z0-9.!?]")
    clean = list(filter(compiled_pattern.match,tokens))
    return clean
tokens = cleanup()

def build_ngrams():
    ngrams = []
    for i in range(len(tokens)-N+1):
        ngrams.append(tokens[i:i+N])
    return ngrams

def ngram_freqs(ngrams):
    counts = {}

    for ngram in ngrams:
        token_seq  = SEP.join(ngram[:-1])
        last_token = ngram[-1]

        if token_seq not in counts:
            counts[token_seq] = {}

        if last_token not in counts[token_seq]:
            counts[token_seq][last_token] = 0

        counts[token_seq][last_token] += 1

    return counts

def next_word(text, N, counts):

    token_seq = SEP.join(text.split()[-(N-1):]);
    choices = counts[token_seq].items();

    total = sum(weight for choice, weight in choices)
    r = random.uniform(0, total)
    upto = 0
    for choice, weight in choices:
        upto += weight
        if upto > r: return choice
    assert False # should not reach here

*** Introductory Examples for the NLTK Book ***
Loading text1, ..., text9 and sent1, ..., sent9
Type the name of the text or sentence to view it.
Type: 'texts()' or 'sents()' to list the materials.
text1: Moby Dick by Herman Melville 1851
text2: Sense and Sensibility by Jane Austen 1811
text3: The Book of Genesis
text4: Inaugural Address Corpus
text5: Chat Corpus
text6: Monty Python and the Holy Grail
text7: Wall Street Journal
text8: Personals Corpus
text9: The Man Who Was Thursday by G . K . Chesterton 1908


In [ ]:
import random

def clean_generated(text):
    text = re.sub(r'\s+([.!?])', r'\1', text)
    
    sentences_list = re.split(r'([.!?]\s*)', text)
    cleaned_sentences = []
    
    for i in range(len(sentences_list)):
        if i == 0 or (i > 0 and re.match(r'[.!?]', sentences_list[i-1])):
            cleaned_sentences.append(sentences_list[i].capitalize())
        else:
            cleaned_sentences.append(sentences_list[i])
            
    return "".join(cleaned_sentences).strip()

N = 5
SEP = " "
sentence_count = 5

ngrams = build_ngrams()
counts = ngram_freqs(ngrams)

start_seq = random.choice(list(counts.keys()))
generated = start_seq.lower()

current_sentences = 0
while current_sentences < sentence_count:
    token_seq = SEP.join(generated.split()[-(N-1):])
    
    if token_seq not in counts:
        token_seq = random.choice(list(counts.keys()))
        generated += SEP + token_seq
    
    word = next_word(generated, N, counts)
    generated += SEP + word

    if word in ['.', '!', '?']:
        current_sentences += 1

generated = clean_generated(generated)
print(generated)

The almost 100 million in financing 0 it is providing the new firm if mr. Cray leaves or if the product-design project 0 he heads is scrapped. The documents also said that cray computer anticipates needing perhaps another 120 million in financing beginning next september. But mr. Barnum called that a worst-case scenario. The filing on the details of the spinoff caused cray research stock to jump 2.875 yesterday to close at 51.25 a share while nl shares closed unchanged at 22.75 and valhi rose 62.5 cents to 15 all in new york stock exchange composite trading yesterday nbi common closed at 93 cents a share up 31 cents. It was richard nixon first visit to china in 1972 that set in motion the historic rapprochement between beijing and washington.
